#!/usr/bin/env bash

function error_and_die() {
  echo -e "tgenv: $(basename ${0}): \033[0;31m[ERROR] ${1}\033[0;39m" >&2
  exit 1
}

function warn_and_continue() {
  echo -e "tgenv: $(basename ${0}): \033[0;33m[WARN] ${1}\033[0;39m" >&2
}

function info() {
  echo -e "\033[0;32m[INFO] ${1}\033[0;39m"
}

# Curl wrapper to switch TLS option for each OS
function curlw () {
  local TLS_OPT="--tlsv1.2"

  # Check if curl is 10.12.6 or above
  if [[ -n "$(command -v sw_vers 2>/dev/null)" && ("$(sw_vers)" =~ 10\.12\.([6-9]|[0-9]{2}) || "$(sw_vers)" =~ 10\.1[3-9]) ]]; then
    TLS_OPT=""
  fi

  curl ${TLS_OPT} "$@"
}

function retry() {
  local command="$1"
  local tries="${2:-5}"
  local sleep="${3:-3}"

  if [[ $# -eq 0 ]] ; then
    echo 'Please insert a function or command as the first argument.'
    exit 1
  fi

  for ((i = 1; i <= tries; i++)); do
    if ((i > 1)); then
      echo "Attempt $((i-1)) failed. Retrying after $sleep seconds..."
      sleep "$sleep"
    fi

    if $command; then
      return 0
    fi
  done

  echo "Command failed after $tries attempts."
  return 1
}
