#!/usr/bin/env bash

[ -n "${TGENV_DEBUG}" ] && set -x

echo "Usage: tgenv <command> [<options>]

Commands:
   install       Install a specific version of Terraform
   use           Switch a version to use
   uninstall     Uninstall a specific version of Terraform
   list          List all installed versions
   list-remote   List all installable versions
"
