#!/usr/bin/env bash

function error_and_die() {
  echo -e "tgenv: ${0}: ${1}" >&2
  exit 1
}

[ -n "${TGENV_DEBUG}" ] && set -x

[ ${#} -ne 0 ] \
  && error_and_die "usage: tgenv list"

[ -d "${TGENV_ROOT}/versions" ] \
  || error_and_die "No versions available. Please install one with: tgenv install"

[[ -x "${TGENV_ROOT}/versions" && -r "${TGENV_ROOT}/versions" ]] \
  || error_and_die "tgenv versions directory is inaccessible!"

ls -1 "${TGENV_ROOT}/versions" | sort -t'.' -k 1nr,1 -k 2nr,2 -k 3nr,3
