#!/usr/bin/env bash

[ -n "${TGENV_DEBUG}" ] && set -x
source "${TGENV_ROOT}/libexec/helpers"

[ "${#}" -gt 1 ] && error_and_die "usage: tgenv install [<version>]"

declare version_requested version regex

if [ -z "${1}" ]; then
  version_file="$(tgenv-version-file)"
  if [ "${version_file}" != "${TGENV_CONFIG_DIR}/version" ]; then
    version_requested="$(cat "${version_file}" || true)"
  fi
else
  version_requested="${1}"
fi

if [[ "${version_requested}" =~ ^latest\:.*$ ]]; then
  version="${version_requested%%\:*}"
  regex="${version_requested##*\:}"
elif [[ "${version_requested}" =~ ^latest$ ]]; then
  version="${version_requested}"
  regex="^[0-9]\+\.[0-9]\+\.[0-9]\+$"
else
  version="${version_requested}"
  regex="^${version_requested}$"
fi

[ -n "${version}" ] || error_and_die "Version is not specified"

dst_path="${TGENV_CONFIG_DIR}/versions/${version}"
if [ -f "${dst_path}/terragrunt" ]; then
  echo "Terragrunt v${version} is already installed"
  exit 0
fi

TGENV_ARCH="${TGENV_ARCH:-amd64}"
case "$(uname -s)" in
  Darwin*)
    os="darwin_${TGENV_ARCH}"
    ;;
  MINGW64*)
    os="windows_${TGENV_ARCH}"
    ;;
  MSYS_NT*)
    os="windows_${TGENV_ARCH}"
    ;;
  CYGWIN_NT*)
    os="windows_${TGENV_ARCH}"
    ;;
  *)
    os="linux_${TGENV_ARCH}"
    ;;
esac

version_url="https://github.com/gruntwork-io/terragrunt/releases/download/v${version}"

tarball_name="terragrunt_${os}";

info "Installing Terragrunt v${version}"

function install() {
  http_code=$(curlw -# --location-trusted -w "%{http_code}" -o "${dst_path}/terragrunt" "${version_url}/${tarball_name}")
  curl_exit_code=$?

  if [[ http_code =~ ^5 ]]; then
    return 1 # fail
  elif [[ http_code =~ ^4 ]]; then
    return 2 # do not retry
  else
    return 0 # success
  fi
}


mkdir -p "${dst_path}" || error_and_die "Failed to make directory ${dst_path}"

info "Downloading release tarball from ${version_url}/${tarball_name}"
retry -tries 5 -sleep 10 -stop-on-exit-code 2 install || error_and_die "Tarball download failed"
install_exist_code=$?

if [ "$install_exist_code" -eq 0 ]; then

  chmod +x "${dst_path}/terragrunt" || error_and_die "Change rights failed"

  info "Installation of terragrunt v${version} successful"
  retry -sleep 3 tgenv-use "${version}" || error_and_die "tgenv use failed"
else
  # make sure versions folder does not exist, so we can retry installation
  rm -rf "${dst_path}"
fi
