#!/usr/bin/env bash
#set -e

function warn_and_continue() {
  echo -e "tgenv: $(basename ${0}): \033[0;33m[WARN] ${1}\033[0;39m" >&2
}

[ -n "${TGENV_DEBUG}" ] && set -x

if [ ${#} -ne 0 ];then
  echo "usage: tgenv list-remote" 1>&2
  exit 1
fi

link_release="https://api.github.com/repos/gruntwork-io/terragrunt/tags?per_page=1000"
print=`curl --tlsv1.2 -sf $link_release`

return_code=$?
if [ $return_code -eq 22 ];then
  warn_and_continue "Failed to get list verion on $link_release"
  print=`cat ${TGENV_ROOT}/list_all_versions_offline`
fi

echo $print | grep -o -E "[0-9]+\.[0-9]+\.[0-9]+(-(rc|beta)[0-9]+)?" | uniq
