#!/usr/bin/env bash

[ -n "${TGENV_DEBUG}" ] && set -x
source "${TGENV_ROOT}/libexec/helpers"

if [ -n "${TGENV_HELPERS:-""}" ]; then
  log 'debug' 'TGENV_HELPERS is set, not sourcing helpers again';
else
  [ "${TGENV_DEBUG:-0}" -gt 0 ] && echo "[DEBUG] Sourcing helpers from ${TGENV_ROOT}/lib/helpers.sh";
  if source "${TGENV_ROOT}/lib/helpers.sh"; then
    log 'debug' 'Helpers sourced successfully';
  else
    early_death "Failed to source helpers from ${TGENV_ROOT}/lib/helpers.sh";
  fi;
fi;

[ "${#}" -ne 0 ] \
  && error_and_die "usage: tgenv list"

[ -d "${TGENV_CONFIG_DIR}/versions" ] \
  || error_and_die "No versions available. Please install one with: tgenv install"

[[ -x "${TGENV_CONFIG_DIR}/versions" && -r "${TGENV_CONFIG_DIR}/versions" ]] \
  || error_and_die "tgenv versions directory is inaccessible!"

print_version () {
    if [ "${1}" == "$(tgenv-version-name)" ]; then
        echo "* ${1} (set by $(tgenv-version-file))"
    else
        echo "  ${1}"
    fi
}

for local_version in $(ls -1 "${TGENV_CONFIG_DIR}/versions" | sort -t'.' -k 1nr,1 -k 2nr,2 -k 3nr,3); do
    print_version "${local_version}"
done
