#!/usr/bin/env bash

[ -n "${TGENV_DEBUG}" ] && set -x
source "${TGENV_ROOT}/libexec/helpers"

[ "${#}" -ne 0 ] \
  && error_and_die "usage: tgenv list"

[ -d "${TGENV_ROOT}/versions" ] \
  || error_and_die "No versions available. Please install one with: tgenv install"

[[ -x "${TGENV_ROOT}/versions" && -r "${TGENV_ROOT}/versions" ]] \
  || error_and_die "tgenv versions directory is inaccessible!"

print_version () {
    if [ "${1}" == "$(tgenv-version-name)" ]; then
        echo "* ${1} (set by $(tgenv-version-file))"
    else
        echo "  ${1}"
    fi
}

for local_version in $(ls -1 "${TGENV_ROOT}/versions" | sort -t'.' -k 1nr,1 -k 2nr,2 -k 3nr,3); do
    print_version "${local_version}"
done
